spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/piris
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver